# Generated by Django 5.2.15 on 2026-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
